config/routes.rb
Paths::Application.routes.draw do

  get 'tags/:tag', to: 'resources#index', as: :tag
  resources :resources

  root :to => 'courses#new'

  resources :restypes

  resources :levels

  resources :courses

  

end

app/models/course.rb
class Course < ActiveRecord::Base

  # has_many :courses_resources
  # has_many :resources, :through => :courses_resources
  
  # acts_as_taggable
  acts_as_taggable_on :units

  def resources_tagged_with_units
    Resource.tagged_with(self.unit_list, :any => true)
  end

end

app/models/courses_resource.rb
class CoursesResource < ActiveRecord::Base
  belongs_to :resource
  belongs_to :course
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  
  # has_many :courses_resources
  # has_many :courses, :through => :courses_resources

  LEVELS = ["intro", "intermediate", "advanced"]
  RESOURCE_TYPES = ["video", "tutorial", "document", "miscelaneous"]
  
  acts_as_taggable
  acts_as_taggable_on :units, :levels, :resource_types, :costs

  def upcase_unit_list
    self.unit_list.each do |u| 
      u.upcase!
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # authenticates_with_sorcery!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @resource = Resource.new(:unit_list => @course.unit_list)
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :description, :unit_list)
    end

    def url_with_protocol(url)
      /^http/.match(url) ? url : "http://#{url}"
    end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

  def create
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]
  
  # GET /resources
  # GET /resources.json
  def index
      if params[:tag]
        @resources = Resource.tagged_with(params[:tag])
      else
      @resources = Resource.all
    end
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
    # @resource = Resource.new(:unit_list => @course.unit_list)
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)
    @resource.unit_list = params[:resource][:unit_list].join(",")
    @resource.level_list = params[:resource][:level_list].join(",")
    @resource.resource_type_list = params[:resource][:resource_type_list].join(",")
    # @resource.cost_list = params[:resource][:cost_list].join(",")

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resource }
      else
        format.html { render action: 'new' }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:name, :provider, :link, :duration, :unit_list, :level_list, :resource_type_list, :cost_list)
    end

  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <br>
  <div class="course-container">
      <%= f.text_field :title, :id => "new-course-form", :placeholder => "Start by Creating a New Course"%>
        <br>
  </div>

  <br>

  <div class="new-unit-field">
    <%= f.text_field :unit_list, :id => "new-unit-form", :placeholder => "Add Units"%>
    <%= f.submit "Create", :id => "btn-submit-unit"%>
  </div>

  <div id="resources-form">
    
  </div>

<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<table>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <!-- <td><%= course.unit_list %></td> -->
        <td><%= raw course.unit_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        <td></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= link_to 'New Course', new_course_path %>
</div>

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p id="course-title">

  <%= @course.title%>
</p>
  <section id="options" class="clearfix combo-filters">

    <div class="option-combo unit">
      <!-- <h4>Unit</h4> -->
      <ul class="filter option-set clearfix" data-filter-group="unit">
        <li><a href="#" data-filter-value="" class="selected">All Units</a></li>
        <% @course.unit_list.each do |u| %>
          <li><a href="#" data-filter-value=".<%= u %>"><%= u.upcase %></a></li>
        <% end %> 
      </ul>
    </div>

    <div class="option-combo level">
      <!-- <h4>Level</h4> -->
      <ul class="filter option-set clearfix" data-filter-group="level">
        <li><a href="#" data-filter-value="" class="selected">All Levels</a></li>
        <% Resource::LEVELS.each do |l| %>
          <li><a href="#" data-filter-value=".<%= l %>"><%= l.upcase %></a></li>
        <% end %> 
      </ul>
    </div>

    <div class="option-combo rtype">
      <!-- <h4>Resource Type</h4> -->
      <ul class="filter option-set clearfix" data-filter-group="rtype">
        <li><a href="#" data-filter-value="" class="selected">All Resource Types</a></li>
        <% Resource::RESOURCE_TYPES.each do |rt| %>
          <li><a href="#" data-filter-value=".<%= rt %>"><%= rt.upcase %></a></li>
        <% end %> 
      </ul>
    </div>

  <!-- <div id="new-resource-btn"> -->
    <a href="#" id="new-resource-btn">Add Resource</a>
  <!-- </div> -->

  </section>

    <div id="container" class="clearfix">
    <% @course.resources_tagged_with_units.each do |r| %>
      <% categories = r.unit_list.join(" ") %> 
      <% levels = r.level_list.join(" ") %> 
      <% rtypes = r.resource_type_list.join(" ") %>
      <div class="unit-level <%= categories %> <%= levels %> <%= rtypes %>">
        <%= link_to r.name, resource_path(r), :remote => true, :class => "res-link" %>
      </div>
    <% end  %>
    </div>
</div>
  
  <div id="resource-container">

    <div id="resource-form-container">
      <%= render "/resources/resource_form" %> 
    </div>

    <div id="resource-show-container">
    </div>
    
  </div>



<%#
<%= link_to 'Edit', edit_course_path(@course) %>
<%# <%= link_to 'Back', courses_path %>

app/views/landing/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Paths</title>
</head>
<body>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paths</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="body paths clearfix">
  <a href="/"><img class="logo" src="/images/logo.png" data-rimage data-src="images/logo.png"></a>

  <div class="menubar"></div>
  <div class="slogan">Your Personal Learning Journey</div>
<br>
<%= yield %>

</body>
</html>

app/views/resources/_form.html.erb
  <div class "container_resource">
    <h2> Add resource </h2>

    <%= form_for(@resource) do |f| %>
      <% if @resource.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

          <ul>
          <% @resource.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
    <% end %>

<div id="new-resource-form">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :provider %><br>
      <%= f.text_area :provider %>
    </div>
    <div class="field">
      <%= f.label :link %><br>
      <%= f.text_area :link %>
    </div>
    <div class="field">
      <%= f.label :duration %><br>
      <%= f.number_field :duration %>
    </div>
    <div id="input-row">
      <%= f.label :unit_list, "Units Available" %><br>
      <%= f.text_field :unit_list %>
    </div>
    <div class="field">
      <%= f.label :level_list, "Levels" %><br>
      <%= f.select :level_list, options_for_select(Resource::LEVELS), {}, {:multiple => true} %>
    </div>
    <div class="field">
      <%= f.label :resource_type_list, "Resource Type (separated by commas)" %><br>
      <%= f.select :resource_type_list, options_for_select(["Tutorial", "Video", "Document", "Miscelaneous"]), {}, {:multiple => true} %>
    </div>
      <div class="field">
      <%= f.label :cost_list, "Free or Paid" %><br>
       <%= f.select :cost_list, options_for_select(["Free", "Paid"]), {}, {:multiple => false} %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <% end %>

  <script>
    $(document).ready(function() {
      var my_tags = @resource.unit_list
      $("#input-row").select2({tags:["Red","Blue","Green"] });
    });
  </script>

</div>

app/views/resources/_resource_form.html.erb
  <div class="resource-form">
    <%= form_for(@resource) do |f| %>
      <% if @resource.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

          <ul>
          <% @resource.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :provider %><br>
      <%= f.text_area :provider %>
    </div>
    <div class="field">
      <%= f.label :link %><br>
      <%= f.text_area :link %>
    </div>
    <div class="field">
      <%= f.label :duration %><br>
      <%= f.number_field :duration %>
    </div>

    <div class="field">
      <%= f.label :unit_list, "Units Available" %><br>
      <%= f.select :unit_list, options_for_select(@course.unit_list), {}, {:multiple => true} %>
    </div>
    <div class="field">
      <%= f.label :level_list, "Levels" %><br>
      <%= f.select :level_list, options_for_select(["Intro", "Intermediate", "Advanced"]), {}, {:multiple => true} %>
    </div>
    <div class="field">
      <%= f.label :resource_type_list, "Resource Type (separated by commas)" %><br>
      <%= f.select :resource_type_list, options_for_select(["Tutorial", "Video", "Document", "Miscelaneous"]), {}, {:multiple => true} %>
    </div>
      <div class="field">
      <%= f.label :cost_list, "Free or Paid" %><br>
       <%= f.select :cost_list, options_for_select(["Free", "Paid"]), {}, {:multiple => false} %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/resources/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @resource.provider %>
</p>

<p>
  <strong>Link:</strong>
  <%= link_to @resource.link, @resource.link %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @resource.duration %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @resource.unit_list%>
</p>

<p>
  <strong>Level:</strong>
  <%= @resource.level_list%>
</p>
<p>
  <strong>Resource Type:</strong>
  <%= @resource.resource_type_list%>
</p>
<p>
  <strong>Cost:</strong>
  <%= @resource.cost_list%>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table class="resources-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Provider</th>
      <th>Link</th>
      <th>Duration</th>
      <th>Units</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.provider %></td>
        <td><%= resource.link %></td>
        <td><%= resource.duration %></td>
        <td><%= raw resource.unit_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @resource.provider %>
</p>

<p>
  <strong>Link:</strong>
  <%= link_to @resource.link, @resource.link %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @resource.duration %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @resource.unit_list%>
</p>

<p>
  <strong>Level:</strong>
  <%= @resource.level_list%>
</p>
<p>
  <strong>Resource Type:</strong>
  <%= @resource.resource_type_list%>
</p>
<p>
  <strong>Cost:</strong>
  <%= @resource.cost_list%>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/resources/show.js.erb
$("#resource-form-container").hide();
$("#resource-show-container").html("<%= escape_javascript(render :partial => 'resources/show') %>");
$("#resource-show-container").show();

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>